### PR TITLE
Fixed docstrings | Added workflow for unit testing automation | Added more test cases | replaced pytest with unittest | Fixed dependencies bugs | 

### PR DESCRIPTION
**Pull request by spirosmaggioros**
I replaced pytest with unittest library as i think for what we have right now on the repo it's easier for the workflow and for adding new unit tests.

There was some issues with the dependencies in dev-dependencies.txt and i updated some libraries to work for macos as well. I will update the workflow for multi-os support soon, i just wanted to tick the boxes right now for the unit testing automation. Right now it builds only for ubuntu-latest.

I also removed unused code, mostly unused parameters in functions and updated the docstrings wherever i could. I will add more docstrings and update the documentation manually the next days as well. 

I also added a couple of test cases, i'm just waiting for this PR to merge to make anohter one, because if something from there wont actually merge to the main branch we will have conflicts.

### CODE REVIEW

**Comment by spirosmaggioros** [comment]
I reverted my additions for documentation files and created a different PR for those changes.

**Comment by spirosmaggioros** [comment]
I debugged the workflows using the additional test cases that i wrote. I will wait for this PR to be merged to make the new PR for the new test cases.
I also have 2 new workflows ready:
- [X] Codecov coverage
- [X] Sphinx automatic documentation

I will make seperate PR's for them as well.

**Review by AlexanderGetka-cbica — APPROVED** [review]
Looks good. Thanks Spiros.

**Comment by AlexanderGetka-cbica** [comment]
Just waiting for the actions to run, then we'll merge.

**Comment by spirosmaggioros** [comment]
Note: I discussed the test cases with george and we concluded that we will use pytest, so i will change them again in the future. Right now we must concentrate to the code readability and syntax as well as the repo presentation

**Pull request merged**
